definitions:
  subscriptions_internal_model.Subscription:
    properties:
      end_date:
        type: string
      id:
        type: string
      price:
        type: integer
      service_name:
        type: string
      start_date:
        description: формат "07-2025"
        type: string
      user_id:
        type: string
    type: object
  subscriptions_internal_model.SubscriptionReq:
    properties:
      end_date:
        description: EndDate optional subscription end date in MM-YYYY format
        type: string
      price:
        description: |-
          Price subscription price, must be positive
          required: true
        type: integer
      service_name:
        description: |-
          ServiceName is the name of the subscription service
          required: true
        type: string
      start_date:
        description: |-
          StartDate subscription start date in MM-YYYY format
          required: true
        example: 07-2025
        type: string
      user_id:
        description: |-
          UserID owner of the subscription (UUID)
          required: true
        type: string
    required:
    - price
    - service_name
    - start_date
    - user_id
    type: object
info:
  contact: {}
paths:
  /subscriptions:
    get:
      description: Get all subscriptions optionally filtered by user_id and service_name,
        with pagination
      parameters:
      - description: Filter by user UUID
        in: query
        name: user_id
        type: string
      - description: Filter by service name
        in: query
        name: service_name
        type: string
      - default: 20
        description: Max number of records to return
        in: query
        name: limit
        type: integer
      - default: 0
        description: Number of records to skip
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Paginated list of subscriptions
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List subscriptions
      tags:
      - subscriptions
    post:
      consumes:
      - application/json
      description: Create a subscription with service name, price, user ID, start
        and optional end dates
      parameters:
      - description: Subscription request body
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/subscriptions_internal_model.SubscriptionReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/subscriptions_internal_model.Subscription'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new subscription
      tags:
      - subscriptions
  /subscriptions/{id}:
    delete:
      description: Delete subscription by UUID
      parameters:
      - description: Subscription ID (UUID)
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete subscription by ID
      tags:
      - subscriptions
    get:
      description: Get details of a subscription by its UUID
      parameters:
      - description: Subscription ID (UUID)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/subscriptions_internal_model.Subscription'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get subscription by ID
      tags:
      - subscriptions
    put:
      consumes:
      - application/json
      description: Update subscription fields by subscription UUID
      parameters:
      - description: Subscription ID (UUID)
        in: path
        name: id
        required: true
        type: string
      - description: Updated subscription data
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/subscriptions_internal_model.SubscriptionReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/subscriptions_internal_model.Subscription'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update subscription by ID
      tags:
      - subscriptions
  /subscriptions/total:
    get:
      description: Calculate total cost for a user and optional service within a date
        range (from, to in MM-YYYY format)
      parameters:
      - description: User UUID
        in: query
        name: user_id
        required: true
        type: string
      - description: Service name
        in: query
        name: service_name
        type: string
      - description: Start period (MM-YYYY)
        in: query
        name: from
        type: string
      - description: End period (MM-YYYY)
        in: query
        name: to
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: integer
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Calculate total subscription cost
      tags:
      - subscriptions
swagger: "2.0"
